IyBuZ2lueCBDb25maWd1cmF0aW9uIEZpbGUKIyBodHRwczovL3dpa2kubmdpbngub3JnL0NvbmZp
Z3VyYXRpb24KCiMgUnVuIGFzIGEgbGVzcyBwcml2aWxlZ2VkIHVzZXIgZm9yIHNlY3VyaXR5IHJl
YXNvbnMuCnVzZXIgbmdpbng7Cgp3b3JrZXJfcHJvY2Vzc2VzIGF1dG87CgpldmVudHMgewogIHdv
cmtlcl9jb25uZWN0aW9ucyAxMDI0Owp9CgpwaWQgICAgICAgIC92YXIvcnVuL25naW54LnBpZDsK
Cmh0dHAgewoKICAgICNSZWRpcmVjdCB0byBodHRwcywgdXNpbmcgMzA3IGluc3RlYWQgb2YgMzAx
IHRvIHByZXNlcnZlIHBvc3QgZGF0YQoKICAgIHNlcnZlciB7CiAgICAgICAgbGlzdGVuIFs6Ol06
NDQzIHNzbDsKICAgICAgICBsaXN0ZW4gNDQzIHNzbDsKCiAgICAgICAgc2VydmVyX25hbWUgbG9j
YWxob3N0OwoKICAgICAgICAjIFByb3RlY3QgYWdhaW5zdCB0aGUgQkVBU1QgYXR0YWNrIGJ5IG5v
dCB1c2luZyBTU0x2MyBhdCBhbGwuIElmIHlvdSBuZWVkIHRvIHN1cHBvcnQgb2xkZXIgYnJvd3Nl
cnMgKElFNikgeW91IG1heSBuZWVkIHRvIGFkZAogICAgICAgICMgU1NMdjMgdG8gdGhlIGxpc3Qg
b2YgcHJvdG9jb2xzIGJlbG93LgogICAgICAgIHNzbF9wcm90b2NvbHMgICAgICAgICAgICAgIFRM
U3YxLjI7CgogICAgICAgICMgQ2lwaGVycyBzZXQgdG8gYmVzdCBhbGxvdyBwcm90ZWN0aW9uIGZy
b20gQmVhc3QsIHdoaWxlIHByb3ZpZGluZyBmb3J3YXJkaW5nIHNlY3JlY3ksIGFzIGRlZmluZWQg
YnkgTW96aWxsYSAtIGh0dHBzOi8vd2lraS5tb3ppbGxhLm9yZy9TZWN1cml0eS9TZXJ2ZXJfU2lk
ZV9UTFMjTmdpbngKICAgICAgICBzc2xfY2lwaGVycyAgICAgICAgICAgICAgICBFQ0RIRS1SU0Et
QUVTMTI4LUdDTS1TSEEyNTY6RUNESEUtRUNEU0EtQUVTMTI4LUdDTS1TSEEyNTY6RUNESEUtUlNB
LUFFUzI1Ni1HQ00tU0hBMzg0OkVDREhFLUVDRFNBLUFFUzI1Ni1HQ00tU0hBMzg0OkRIRS1SU0Et
QUVTMTI4LUdDTS1TSEEyNTY6REhFLURTUy1BRVMxMjgtR0NNLVNIQTI1NjprRURIK0FFU0dDTTpF
Q0RIRS1SU0EtQUVTMTI4LVNIQTI1NjpFQ0RIRS1FQ0RTQS1BRVMxMjgtU0hBMjU2OkVDREhFLVJT
QS1BRVMxMjgtU0hBOkVDREhFLUVDRFNBLUFFUzEyOC1TSEE6RUNESEUtUlNBLUFFUzI1Ni1TSEEz
ODQ6RUNESEUtRUNEU0EtQUVTMjU2LVNIQTM4NDpFQ0RIRS1SU0EtQUVTMjU2LVNIQTpFQ0RIRS1F
Q0RTQS1BRVMyNTYtU0hBOkRIRS1SU0EtQUVTMTI4LVNIQTI1NjpESEUtUlNBLUFFUzEyOC1TSEE6
REhFLURTUy1BRVMxMjgtU0hBMjU2OkRIRS1SU0EtQUVTMjU2LVNIQTI1NjpESEUtRFNTLUFFUzI1
Ni1TSEE6REhFLVJTQS1BRVMyNTYtU0hBOkFFUzEyOC1HQ00tU0hBMjU2OkFFUzI1Ni1HQ00tU0hB
Mzg0OkVDREhFLVJTQS1SQzQtU0hBOkVDREhFLUVDRFNBLVJDNC1TSEE6QUVTMTI4OkFFUzI1NjpS
QzQtU0hBOkhJR0g6IWFOVUxMOiFlTlVMTDohRVhQT1JUOiFERVM6ITNERVM6IU1ENTohUFNLOwog
ICAgICAgIHNzbF9wcmVmZXJfc2VydmVyX2NpcGhlcnMgIG9uOwoKICAgICAgICAjIE9wdGltaXpl
IFRMUy9TU0wgYnkgY2FjaGluZyBzZXNzaW9uIHBhcmFtZXRlcnMgZm9yIDEwIG1pbnV0ZXMuIFRo
aXMgY3V0cyBkb3duIG9uIHRoZSBudW1iZXIgb2YgZXhwZW5zaXZlIFRMUy9TU0wgaGFuZHNoYWtl
cy4KICAgICAgICAjIFRoZSBoYW5kc2hha2UgaXMgdGhlIG1vc3QgQ1BVLWludGVuc2l2ZSBvcGVy
YXRpb24sIGFuZCBieSBkZWZhdWx0IGl0IGlzIHJlLW5lZ290aWF0ZWQgb24gZXZlcnkgbmV3L3Bh
cmFsbGVsIGNvbm5lY3Rpb24uCiAgICAgICAgIyBCeSBlbmFibGluZyBhIGNhY2hlIChvZiB0eXBl
ICJzaGFyZWQgYmV0d2VlbiBhbGwgTmdpbnggd29ya2VycyIpLCB3ZSB0ZWxsIHRoZSBjbGllbnQg
dG8gcmUtdXNlIHRoZSBhbHJlYWR5IG5lZ290aWF0ZWQgc3RhdGUuCiAgICAgICAgIyBGdXJ0aGVy
IG9wdGltaXphdGlvbiBjYW4gYmUgYWNoaWV2ZWQgYnkgcmFpc2luZyBrZWVwYWxpdmVfdGltZW91
dCwgYnV0IHRoYXQgc2hvdWxkbid0IGJlIGRvbmUgdW5sZXNzIHlvdSBzZXJ2ZSBwcmltYXJpbHkg
SFRUUFMuCiAgICAgICAgc3NsX3Nlc3Npb25fY2FjaGUgICAgc2hhcmVkOlNTTDoxMG07ICMgYSAx
bWIgY2FjaGUgY2FuIGhvbGQgYWJvdXQgNDAwMCBzZXNzaW9ucywgc28gd2UgY2FuIGhvbGQgNDAw
MDAgc2Vzc2lvbnMKICAgICAgICBzc2xfc2Vzc2lvbl90aW1lb3V0ICAyNGg7CgoKICAgICAgICAj
IFVzZSBhIGhpZ2hlciBrZWVwYWxpdmUgdGltZW91dCB0byByZWR1Y2UgdGhlIG5lZWQgZm9yIHJl
cGVhdGVkIGhhbmRzaGFrZXMKICAgICAgICBrZWVwYWxpdmVfdGltZW91dCAzMDA7ICMgdXAgZnJv
bSA3NSBzZWNzIGRlZmF1bHQKCiAgICAgICAgIyByZW1lbWJlciB0aGUgY2VydGlmaWNhdGUgZm9y
IGEgeWVhciBhbmQgYXV0b21hdGljYWxseSBjb25uZWN0IHRvIEhUVFBTCiAgICAgICAgYWRkX2hl
YWRlciBTdHJpY3QtVHJhbnNwb3J0LVNlY3VyaXR5ICdtYXgtYWdlPTMxNTM2MDAwOyBpbmNsdWRl
U3ViRG9tYWlucyc7CgogICAgICAgIHNzbF9jZXJ0aWZpY2F0ZSAgICAgIC9ldGMvbmdpbngvc3Ns
LmNydDsKICAgICAgICBzc2xfY2VydGlmaWNhdGVfa2V5ICAvZXRjL25naW54L3NzbC5rZXk7Cgog
ICAgICAgIGxvY2F0aW9uIC8gewogICAgICAgICAgICBwcm94eV9wYXNzIGh0dHA6Ly9sb2NhbGhv
c3Q6ODA7CgogICAgICAgICAgICBwcm94eV9zZXRfaGVhZGVyIENvbm5lY3Rpb24gIiI7CiAgICAg
ICAgICAgIHByb3h5X3NldF9oZWFkZXIgSG9zdCAkaG9zdDsKICAgICAgICAgICAgcHJveHlfc2V0
X2hlYWRlciBYLVJlYWwtSVAgJHJlbW90ZV9hZGRyOwogICAgICAgICAgICBwcm94eV9zZXRfaGVh
ZGVyIFgtRm9yd2FyZGVkLUZvciAkcmVtb3RlX2FkZHI7CiAgICAgICAgfQogICAgfQp9
